#:schema node_modules/wrangler/config-schema.json
name = "twikoo"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-01-11"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo-db"
database_id = "719ed1eb-22ff-424d-8dbe-51cbf24e1e9d"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.r2.mingy.org"

[dev]
port = 5000
